import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import suppliersRouter from "./suppliers";
import purchasesRouter from "./purchases";
import lotsRouter from "./lots";
import clientsRouter from "./clients";
import salesRouter from "./sales";
import accountingRouter from "./accounting";
import dashboardRouter from "./dashboard";
import paymentsRouter from "./payments";
import stockMovementsRouter from "./stock-movements";
import employeesRouter from "./employees";
import leavesRouter from "./leaves";
import attendanceRouter from "./attendance";
import hrRequestsRouter from "./hr-requests";
import payrollRouter from "./payroll";
import bonusesRouter from "./bonuses";
import candidatesRouter from "./candidates";
import onboardingRouter from "./onboarding";
import accountingPartnersRouter from "./accounting-partners";
import accountingInvoicesRouter from "./accounting-invoices";
import accountingBankRouter from "./accounting-bank";
import accountingAssetsRouter from "./accounting-assets";
import accountingReportsRouter from "./accounting-reports";
import dashboardRbacRouter from "./dashboard-rbac";
import usersRouter from "./users";
import lotCostsRouter from "./lot-costs";
import aiPredictionRouter from "./ai-prediction";
import logisticsDashboardRouter from "./logistics-dashboard";
import leadsRouter from "./leads";
import crmEmailsRouter from "./crm-emails";
import crmRemindersRouter from "./crm-reminders";
import crmDashboardRouter from "./crm-dashboard";
import prospectsRouter from "./prospects";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(suppliersRouter);
router.use(purchasesRouter);
router.use(lotsRouter);
router.use(clientsRouter);
router.use(prospectsRouter);
router.use(salesRouter);
router.use(accountingRouter);
router.use(dashboardRouter);
router.use(paymentsRouter);
router.use(stockMovementsRouter);
router.use(employeesRouter);
router.use(leavesRouter);
router.use(attendanceRouter);
router.use(hrRequestsRouter);
router.use(payrollRouter);
router.use(bonusesRouter);
router.use(candidatesRouter);
router.use(onboardingRouter);
router.use(accountingPartnersRouter);
router.use(accountingInvoicesRouter);
router.use(accountingBankRouter);
router.use(accountingAssetsRouter);
router.use(accountingReportsRouter);
router.use(dashboardRbacRouter);
router.use(usersRouter);
router.use(lotCostsRouter);
router.use(aiPredictionRouter);
router.use(logisticsDashboardRouter);
router.use(leadsRouter);
router.use(crmEmailsRouter);
router.use(crmRemindersRouter);
router.use(crmDashboardRouter);

export default router;
