import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import suppliersRouter from "./suppliers";
import purchasesRouter from "./purchases";
import lotsRouter from "./lots";
import clientsRouter from "./clients";
import salesRouter from "./sales";
import accountingRouter from "./accounting";
import dashboardRouter from "./dashboard";
import paymentsRouter from "./payments";
import stockMovementsRouter from "./stock-movements";
import employeesRouter from "./employees";
import leavesRouter from "./leaves";
import attendanceRouter from "./attendance";
import hrRequestsRouter from "./hr-requests";
import payrollRouter from "./payroll";
import bonusesRouter from "./bonuses";
import candidatesRouter from "./candidates";
import onboardingRouter from "./onboarding";
import accountingPartnersRouter from "./accounting-partners";
import accountingInvoicesRouter from "./accounting-invoices";
import accountingBankRouter from "./accounting-bank";
import accountingAssetsRouter from "./accounting-assets";
import accountingReportsRouter from "./accounting-reports";
import dashboardRbacRouter from "./dashboard-rbac";
import usersRouter from "./users";
import lotCostsRouter from "./lot-costs";
import aiPredictionRouter from "./ai-prediction";
import logisticsDashboardRouter from "./logistics-dashboard";
import leadsRouter from "./leads";
import crmEmailsRouter from "./crm-emails";
import crmRemindersRouter from "./crm-reminders";
import crmDashboardRouter from "./crm-dashboard";
import prospectsRouter from "./prospects";
import crmClientsRouter from "./crm-clients";
import crmConversionAlertsRouter from "./crm-conversion-alerts";
import dealsRouter from "./deals";
import interactionsRouter from "./interactions";
import quotesRouter from "./quotes";
import importLotsRouter from "./import-lots";
import importProductsRouter from "./import-products";
import productsRouter from "./products";
import productStockRouter from "./product-stock";
import lotStatusRouter from "./lot-status";
import aiRouter from "./ai";
import hrImportRouter from "./hr-import";
import hrDeclarationsRouter from "./hr-declarations";
import departmentsRouter from "./departments";
import settingsRouter from "./settings";
import platformSettingsRouter from "./platform-settings";
import planningRouter from "./planning";
import recruitmentRouter from "./recruitment";
import operationsRouter from "./operations";
import financeRouter from "./finance";
import closingRouter from "./closing";
import invoicePaymentsRouter from "./invoice-payments";
import tiersRouter from "./tiers";
import bankReconciliationRouter from "./bank-reconciliation";
import adminExecutiveRouter from "./admin-executive";
import securityRouter from "./security";
import auth2faRouter from "./auth-2fa";
import backupRouter from "./backup";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(suppliersRouter);
router.use(purchasesRouter);
// lot-status must come BEFORE lots: /lots/risk would otherwise be captured by /lots/:id
router.use(lotStatusRouter);
router.use(lotsRouter);
router.use(clientsRouter);
router.use(prospectsRouter);
router.use(crmClientsRouter);
router.use(crmConversionAlertsRouter);
router.use(dealsRouter);
router.use(interactionsRouter);
router.use(quotesRouter);
router.use(salesRouter);
router.use(accountingRouter);
router.use(dashboardRouter);
router.use(paymentsRouter);
router.use(stockMovementsRouter);
router.use(employeesRouter);
router.use(leavesRouter);
router.use(attendanceRouter);
router.use(hrRequestsRouter);
router.use(payrollRouter);
router.use(bonusesRouter);
router.use(candidatesRouter);
router.use(onboardingRouter);
router.use(accountingPartnersRouter);
router.use(accountingInvoicesRouter);
router.use(accountingBankRouter);
router.use(accountingAssetsRouter);
router.use(accountingReportsRouter);
router.use(dashboardRbacRouter);
router.use(usersRouter);
router.use(lotCostsRouter);
router.use(aiPredictionRouter);
router.use(logisticsDashboardRouter);
router.use(leadsRouter);
router.use(crmEmailsRouter);
router.use(crmRemindersRouter);
router.use(crmDashboardRouter);
router.use(importLotsRouter);
router.use(importProductsRouter);
router.use(productsRouter);
router.use(productStockRouter);
router.use(aiRouter);
router.use(departmentsRouter);
router.use(hrImportRouter);
router.use(hrDeclarationsRouter);
router.use(settingsRouter);
router.use(platformSettingsRouter);
router.use(planningRouter);
router.use(recruitmentRouter);
router.use(operationsRouter);
router.use(financeRouter);
router.use(closingRouter);
router.use(invoicePaymentsRouter);
// tiers must come AFTER accountingPartnersRouter: /tiers/:id before /partners
router.use(tiersRouter);
// bank-reconciliation: new endpoints alongside existing accounting-bank
router.use(bankReconciliationRouter);
router.use(adminExecutiveRouter);
router.use(securityRouter);
router.use(auth2faRouter);
router.use(backupRouter);

export default router;
